"""Generate a small project map for agent context packs."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / ".agent" / "context" / "PROJECT_MAP.md"
TOP_LEVEL = ("core_engine", "harness", "ui", "docs", "scripts")


def list_tree(base: Path, max_depth: int = 3) -> list[str]:
    lines: list[str] = []
    for path in sorted(base.rglob("*")):
        if "__pycache__" in path.parts:
            continue
        relative = path.relative_to(ROOT)
        depth = len(relative.parts)
        if depth > max_depth:
            continue
        prefix = "  " * (depth - 1)
        marker = "/" if path.is_dir() else ""
        lines.append(f"{prefix}- {path.name}{marker}")
    return lines


def main() -> int:
    sections = [
        "# Audio Forge Project Map",
        "",
        "Generated by `scripts/collect_context.py`.",
        "",
        "## Key Directories",
        "",
    ]

    for name in TOP_LEVEL:
        path = ROOT / name
        if not path.exists():
            continue
        sections.append(f"### {name}/")
        sections.extend(list_tree(path))
        sections.append("")

    OUTPUT.write_text("\n".join(sections), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

